#!/bin/sh

#remove obsolete ElectricSheep2.saver if found
if [ -e "$2/ElectricSheep2.saver" ]; then

	rm -rf "$2/ElectricSheep2.saver"

fi

#sets current screen saver the way 10.4 - 10.5 do

sudo -u "$USER" defaults -currentHost write com.apple.screensaver moduleName "Electric Sheep"

sudo -u "$USER" defaults -currentHost write com.apple.screensaver modulePath "$2/Electric Sheep.saver"

#sets current screen saver the way 10.6 does
sudo -u "$USER" defaults -currentHost write com.apple.screensaver moduleDict -dict moduleName "Electric Sheep" path "$2/Electric Sheep.saver" type 0
